name: Build docker image and deploy to server

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      docker_registry_user: ${{ secrets.CI_REGISTRY_USER }}
      docker_registry_password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      #image: djvue/urfu-deployments:pi2-${{ github.ref_name }}
      base_image: djvue/urfu-deployments
      image: djvue/urfu-deployments:pi2-${{ github.sha }}
      image_latest: djvue/urfu-deployments:pi2-tiny-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login into docker hub
      run: docker login -u $docker_registry_user -p "$docker_registry_password"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $image
    - name: Push the Docker streamlit image
      run: docker tag $image $image_latest
    - name: Push the Docker streamlit image
      run: docker push --all-tags $base_image

  deploy:
    name: Deploy to prod host
    needs: build
    runs-on: ubuntu-latest
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      image: djvue/urfu-deployments:pi2-${{ github.sha }}
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -X POST \
            -F token="'$DISPATCH_TOKEN'" \
            -F "ref=master" \
            -F "variables[target]=deploy_home" \
            -F "variables[name]=urfu_pi2" \
            -F "variables[token]='$DEPLOY_TOKEN'" \
            -F "variables[image]='$image'" \
            "https://gitlab.com/api/v4/projects/55744560/trigger/pipeline"